version: "3.8"
services:
  backend:
    image: backend_image
    container_name: backend
    build: 
      context: "./backend"
      dockerfile: "../docker/app/Backend"
    volumes:
      - ./:/app/backend
    ports:
      - "30001:30001"
    networks:
      - backend
  frontend:
    image: frontend_image
    container_name: frontend
    build:
      context: "./frontend"
      dockerfile: "../docker/app/Frontend"
    volumes:
      - ./:/app/frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: always
  db:
    image: mysql:8.0
    container_name: db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'ecommerce'
      MYSQL_USER: 'ecommerce'
      MYSQL_PASSWORD: '1181080029'
      MYSQL_ROOT_PASSWORD: '1181080029'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - "5107:3306"
    networks:
      - backend

volumes:
  mysql-db:

networks:
  backend:
    driver: bridge
    name: backend
