version: "3.8"
services:
  backend:
    image: backend_image
    container_name: backend
    build: 
      context: "./backend"
      dockerfile: "../docker/app/Backend"
    volumes:
      - ./:/app/backend
    ports:
      - "30001:30001"
  frontend:
    image: frontend_image
    container_name: frontend
    build:
      context: "./frontend"
      dockerfile: "../docker/app/Frontend"
    volumes:
      - ./:/app/frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: always