version: "3.8"
services:
  e-backend:
    image: backend_image
    container_name: e-backend
    build:
      context: "./backend"
      dockerfile: "../docker/app/Backend"
    volumes:
      - ./:/app/
    depends_on:
      - e-db
    restart: always
    links:
      - e-db
    ports:
      - "30001:30001"
    networks:
      - backend
  e-frontend:
    image: frontend_image
    container_name: frontend
    build:
      context: "./frontend"
      dockerfile: "../docker/app/Frontend"
    volumes:
      - ./frontend/:/app/
      - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - e-backend
    networks:
      - backend
    restart: always
  e-db:
    image: mysql:8.0
    container_name: e-db
    restart: always
    environment:
      MYSQL_DATABASE: 'ecommerce'
      MYSQL_USER: 'ecommerce'
      MYSQL_PASSWORD: '1181080029'
      MYSQL_ROOT_PASSWORD: '1181080029'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql-db:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    ports:
      - "5107:3306"
    networks:
      - backend

volumes:
  mysql-db:

networks:
  backend:
    driver: bridge
    name: backend
