# Generated by Django 4.2.11 on 2024-03-12 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
    ]
