SET CHARSET UTF8;

INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(1, 'Họa tiết', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(2, 'Loại bảo hành', 1, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(3, 'Thương hiệu', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(4, 'Chất liệu', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(5, 'Loại hộp đựng', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(6, 'Loại da', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(7, 'Chất liệu dây đeo', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(8, 'Khả năng tương thích của Mẫu', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(9, 'Dung lượng Powerbank', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(10, 'Số cổng', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(11, 'Cổng', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(12, 'Các tính năng của Powerbank', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(13, 'Điện áp (V)', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(14, 'Sạc nhanh', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(15, 'Số lượng Bộ sạc', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(16, 'Loại phích cắm', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(17, 'Người mẫu', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(18, 'Các Mẫu Tương thích', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(19, 'Độ phân giải', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(20, 'Dung lượng lưu trữ', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(21, 'Hệ điều hành được Hỗ trợ', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(22, 'Loại cáp', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(23, 'Thời hạn bảo hành', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(24, 'Bó', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(25, 'Điện áp đầu vào (V)', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(26, 'Có pin', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(27, 'Dung lượng pin (mAh)', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(28, 'Có Maganet', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(29, 'Tình trạng sản phẩm', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(30, 'Pin tích hợp', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(31, 'Số lượng pin', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(32, 'Điểm lấy nét Tự động', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(33, 'Kích thước Màn hình', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(34, 'Siêu điểm ảnh', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(35, 'Mẫu Camera', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(36, 'Không thấm nước', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(37, 'Phạm vi Lấy nét Tối thiểu (m)', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(38, 'Phạm vi ISO', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(39, 'Loại pin', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(40, 'Thu phóng Kỹ thuật số', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(41, 'Tỷ lệ Khung', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(42, 'Khẩu độ Tối đa', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(43, 'Loại Thẻ nhớ', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(44, 'Khẩu độ Tối thiểu', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(45, 'Zoom Quang học', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(46, 'Chụp video Nghị quyết', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(47, 'Ống ngắm', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(48, 'Loại Ống kính Camera', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(49, 'Khả năng tương thích với Nhãn hiệu Camera', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(50, 'Dành cho Trò chơi', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(51, 'Loại kết nối', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(52, 'Dành cho Thể thao', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(53, 'Khả năng tương thích Âm thanh', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(54, 'Tai nghe', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(55, 'Tai nghe', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(56, 'Loại Phụ kiện Tai nghe', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(57, 'Loại Kết nối Tai nghe', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(58, 'Phản hồi Tần số Tối đa', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(59, 'Phản hồi Tần số Tối thiểu', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(60, 'Đánh giá Độ nhạy', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(61, 'Loa Thông minh', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(62, 'Bluetooth', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(63, 'Loại âm li', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(64, 'Bộ cắt Âm thanh', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(65, 'Đầu vào', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(66, 'Phạm vi', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(67, 'Số kênh', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(68, 'Kết nối Tai nghe', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(69, 'Nguồn điện', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(70, 'Loại Tai nghe', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(71, 'Mức tiêu thụ điện (W)', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(72, 'Độ sáng Máy chiếu', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(73, 'Tỷ lệ Tương phản', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(74, 'Các tính năng của Máy chiếu', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(75, 'Loại Máy chiếu', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(76, 'Loại Bảng điều khiển Trò chơi', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(77, 'Kết nối', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(78, 'Khả năng tương thích Nền tảng', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(79, 'Đường kính Vỏ Đồng hồ', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(80, 'Kích thước Màn hình (inch)', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(81, 'Đồng hồ Thông minh', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(82, 'Độ phân giải Camera Chính', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(83, 'Chất liệu dây đeo', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(84, 'Xem Kết nối', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(85, 'Bảng điều khiển Tương thích', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(86, 'RAM', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(87, 'Số lượng pin', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(88, 'NFC', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(89, 'Màu sắc', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(90, 'Số lượng Khe cắm Thẻ SIM', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(91, 'Loại Điện thoại', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(92, 'Trọng lượng (g)', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(93, 'Vi xử lý', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(94, 'Số lõi', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(95, 'Loại SIM', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(96, 'Giắc cắm 3,5 mm', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(97, 'Loại cáp', 4, now(), now()); -- thừa
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(98, 'Năm phát hành', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(99, 'CPU (Ghz)', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(100, 'Ổ đĩa quang', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(101, 'Loại bảo quản', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(102, 'Mẫu Máy tính xách tay', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(103, 'Nhà sản xuất Chipset Đồ họa', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(104, 'Kích thước Màn hình Máy tính xách tay', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(105, 'Loại máy tính xách tay', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(106, 'Hệ điều hành', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(107, 'Loại bảng LED', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(108, 'Kích thước Màn hình Điều khiển', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(109, 'Giám sát Thời gian Phản hồi (ms)', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(110, 'Cổng Giám sát', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(111, 'Điện áp', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(112, 'DDR', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(113, 'Số lượng Lõi CPU', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(114, 'Chipset CPU', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(115, 'Đánh giá Công suất', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(116, 'Đánh giá Hiệu suất PSU', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(117, 'Khả năng tương thích của Bo mạch chủ', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(118, 'Bên trong/Bên ngoài', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(119, 'Tốc độ Đọc (Mb/s)', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(120, 'Phương tiện Tương thích', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(121, 'Chế độ Đầu ra Âm thanh', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(122, 'Nước xuất xứ', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(123, 'Mẫu Bàn phím & Chuột', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(124, 'Các tính năng của Cáp', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(125, 'Micro Tích hợp sẵn', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(126, 'Khả năng tương thích với Thương hiệu Bộ sạc Máy tính xách tay', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(127, 'Chiều dài Cáp (m)', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(128, 'Loại Bộ điều hợp', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(129, 'Loại Bút', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(130, 'Tốc độ Quay', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(131, 'Hệ số hình thức SSD', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(132, 'Số lượng Nhịp', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(133, 'Loại Tốc độ Bộ nhớ Flash', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(134, 'Loại Bộ nhớ Flash', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(135, 'Kích thước Vỏ Đĩa cứng (inch)', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(136, 'Số lượng Anten', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(137, 'Loại Ăng ten', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(138, 'Tốc độ Modem (Mbps)', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(139, 'Mạng Không dây', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(140, 'Tốc độ Mạng', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(141, 'Loại Công tắc Mạng', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(142, 'Loại Đầu nối & Cáp mạng', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(143, 'Loại két sắt', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(144, 'Thiết bị thông minh', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(145, 'Tính năng Đồng hồ', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(146, 'Kiểu Theo dõi', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(147, 'Tính năng VR', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(148, 'Tiêu chuẩn Giao tiếp Mạng', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(149, 'Giám sát Thời gian Phản hồi (ms)', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(150, 'Cài đặt', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(151, 'Sử dụng', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(152, 'Số lượng mỗi gói', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(153, 'Đặc điểm', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(154, 'Hình dạng', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(155, 'Phong cách', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(156, 'Kẹp', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(157, 'Số lớp', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(158, 'Trả góp', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(159, 'Trọng lượng hỗ trợ (kg)', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(160, 'Xếp đặt', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(161, 'Số lượng', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(162, 'Tuổi đời sản phẩm', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(163, 'Loại bàn chải toilet', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(164, 'Mùa', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(165, 'Loại bọc ghế nhà vệ sinh', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(166, 'Loại khay đựng xà phòng', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(167, 'Tuổi', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(168, 'Loại giá đỡ bàn chải đánh răng', 4, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(169, 'Loại thanh treo rèm phòng tắm', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(170, 'Loại đĩa xà phòng', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(171, 'Loại bồn tắm', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(172, 'Giới tính', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(173, 'Loại khăn', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(174, 'Loại tiện ích phòng tắm', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(175, 'Bộ phận cơ thể', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(176, 'Loại phụ kiện phòng tắm', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(177, 'Hướng dẫn giặt', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(178, 'Điểm ảnh', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(179, 'Mẫu Ống kính', 0, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(180, 'Loại loa', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(181, 'Loại phụ kiện', 3, now(), now());
INSERT IGNORE INTO properties (id, name, type, created_at, updated_at) VALUES(182, 'Phiên bản', 0, now(), now());
